/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.JOptionPane;

/**
 *
 * @author WINDOWS 11 PRO
 */
public class DashboardFrame extends javax.swing.JFrame {
    
    // VARIABEL UNTUK MENYIMPAN STATUS LOGIN
    private boolean isLoggedIn = false;
    
    // METHOD BARU: Digunakan untuk semua menu item yang perlu dicek
    private boolean checkLoginAndRedirect() {
        if (!isLoggedIn) {
            JOptionPane.showMessageDialog(this, "Anda harus Login terlebih dahulu untuk mengakses menu ini.");
            
            // REDIRECT ke LoginFrame
            new LoginFrame().setVisible(true); 
            this.dispose(); 
            return false; // Gagal, harus kembali
        }
        return true; // Sukses, lanjutkan aksi
    }
    
    // METHOD UTAMA: Mengatur Status Menu dan Statistik
    public void checkLoginStatus(boolean status) {
        this.isLoggedIn = status; // Simpan status
        
        // 1. Kunci/Buka Menu Bar
        masterDataMenu.setEnabled(status); // true = BUKA
        transaksiMenu.setEnabled(status); // true = BUKA
        laporanMenu.setEnabled(status);   // true = BUKA

        // 2. Kontrol Menu Login/Logout (aplikasiMenu)
        loginMenuItem.setEnabled(!status);  // Login: Aktif jika BELUM Login
        logoutMenuItem.setEnabled(status);  // Logout: Aktif jika SUDAH Login

        // 3. Update Statistik dan Teks
        if (status) {
            // Ketika TRUE (SUDAH LOGIN)
            loadStatistik(); 
        } else {
            // Ketika FALSE (BELUM LOGIN)
            txtKamarKosong.setText("LOGIN DULU");
            txtTotalPenghuni.setText("LOGIN DULU");
        }
    } 
    
    private void loadStatistik() {
        try {
            java.sql.Connection conn = config.koneksi.configDB();
            
            // Kamar Kosong
            String sqlKosong = "SELECT COUNT(*) FROM kamar WHERE status='Kosong'";
            java.sql.ResultSet resKosong = conn.createStatement().executeQuery(sqlKosong);
            if (resKosong.next()) {
                txtKamarKosong.setText(resKosong.getString(1) + " Kamar Kosong");
            }

            // Penghuni Aktif
            String sqlPenghuni = "SELECT COUNT(*) FROM sewa";
            java.sql.ResultSet resPenghuni = conn.createStatement().executeQuery(sqlPenghuni);
            if (resPenghuni.next()) {
                txtTotalPenghuni.setText(resPenghuni.getString(1) + " Penghuni Aktif");
            }
            
        } catch (Exception e) {
            System.err.println("Error memuat statistik: " + e.getMessage());
        }
    }

    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame() {
        initComponents();
        checkLoginStatus(false); // Kunci semua menu saat start-up
        
        txtKamarKosong.setEditable(false);
        txtTotalPenghuni.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtKamarKosong = new javax.swing.JTextField();
        txtTotalPenghuni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        aplikasiMenu = new javax.swing.JMenu();
        loginMenuItem = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();
        masterDataMenu = new javax.swing.JMenu();
        dataKamarMenuItem = new javax.swing.JMenuItem();
        dataPenghuniMenuItem = new javax.swing.JMenuItem();
        transaksiMenu = new javax.swing.JMenu();
        sewaKamarMenuItem = new javax.swing.JMenuItem();
        pembayaranMenuItem = new javax.swing.JMenuItem();
        laporanMenu = new javax.swing.JMenu();
        riwayatSewaMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dashboard", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELAMAT DATANG DI KOS-IN");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data penghuni");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data kamar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(47, 47, 47))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtKamarKosong, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(51, 51, 51)
                        .addComponent(txtTotalPenghuni, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel2)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKamarKosong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotalPenghuni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        aplikasiMenu.setText("Aplikasi");

        loginMenuItem.setText("Login");
        loginMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginMenuItemActionPerformed(evt);
            }
        });
        aplikasiMenu.add(loginMenuItem);

        logoutMenuItem.setText("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        aplikasiMenu.add(logoutMenuItem);

        jMenuBar1.add(aplikasiMenu);

        masterDataMenu.setText("Master Data");

        dataKamarMenuItem.setText("Data Kamar");
        dataKamarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataKamarMenuItemActionPerformed(evt);
            }
        });
        masterDataMenu.add(dataKamarMenuItem);

        dataPenghuniMenuItem.setText("Data Penghuni");
        dataPenghuniMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataPenghuniMenuItemActionPerformed(evt);
            }
        });
        masterDataMenu.add(dataPenghuniMenuItem);

        jMenuBar1.add(masterDataMenu);

        transaksiMenu.setText("Transaksi");

        sewaKamarMenuItem.setText("Sewa Kamar");
        sewaKamarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sewaKamarMenuItemActionPerformed(evt);
            }
        });
        transaksiMenu.add(sewaKamarMenuItem);

        pembayaranMenuItem.setText("Pembayaran");
        pembayaranMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaranMenuItemActionPerformed(evt);
            }
        });
        transaksiMenu.add(pembayaranMenuItem);

        jMenuBar1.add(transaksiMenu);

        laporanMenu.setText("Laporan");

        riwayatSewaMenuItem.setText("Riwayat");
        riwayatSewaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riwayatSewaMenuItemActionPerformed(evt);
            }
        });
        laporanMenu.add(riwayatSewaMenuItem);

        jMenuBar1.add(laporanMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataPenghuniMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataPenghuniMenuItemActionPerformed
        // TODO add your handling code here:
        if (!checkLoginAndRedirect()) return;
        new PenghuniFrame().setVisible(true);
    }//GEN-LAST:event_dataPenghuniMenuItemActionPerformed

    private void pembayaranMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaranMenuItemActionPerformed
        // TODO add your handling code here:
        if (!checkLoginAndRedirect()) return;
        new PembayaranFrame().setVisible(true);
    }//GEN-LAST:event_pembayaranMenuItemActionPerformed

    private void loginMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMenuItemActionPerformed
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        this.dispose(); //
    }//GEN-LAST:event_loginMenuItemActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        // TODO add your handling code here:
        // Aksi ini hanya aktif jika SUDAH login (logika di checkLoginStatus)
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin Logout?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    
        if (konfirmasi == JOptionPane.YES_OPTION) {
            checkLoginStatus(false); // Set status logout (mengunci menu)
            this.dispose(); 
            new LoginFrame().setVisible(true); 
        }
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void dataKamarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataKamarMenuItemActionPerformed
        // TODO add your handling code here:
        if (!checkLoginAndRedirect()) return;
        new KamarFrame().setVisible(true);
    }//GEN-LAST:event_dataKamarMenuItemActionPerformed

    private void sewaKamarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sewaKamarMenuItemActionPerformed
        // TODO add your handling code here:
        if (!checkLoginAndRedirect()) return;
        // PERBAIKAN: Memanggil SewaFrame
        new SewaFrame().setVisible(true);   
    }//GEN-LAST:event_sewaKamarMenuItemActionPerformed

    private void riwayatSewaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riwayatSewaMenuItemActionPerformed
        // TODO add your handling code here:
        // 1. Cek apakah user sudah login
    if (!checkLoginAndRedirect()) return;
    
    // 2. Buka Frame Laporan/Riwayat
    // Pastikan Anda sudah membuat class LaporanSewaFrame.java
    new LaporanSewaFrame().setVisible(true);
    }//GEN-LAST:event_riwayatSewaMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aplikasiMenu;
    private javax.swing.JMenuItem dataKamarMenuItem;
    private javax.swing.JMenuItem dataPenghuniMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu laporanMenu;
    private javax.swing.JMenuItem loginMenuItem;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenu masterDataMenu;
    private javax.swing.JMenuItem pembayaranMenuItem;
    private javax.swing.JMenuItem riwayatSewaMenuItem;
    private javax.swing.JMenuItem sewaKamarMenuItem;
    private javax.swing.JMenu transaksiMenu;
    private javax.swing.JTextField txtKamarKosong;
    private javax.swing.JTextField txtTotalPenghuni;
    // End of variables declaration//GEN-END:variables
}
