/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.JOptionPane;

/**
 *
 * @author WINDOWS 11 PRO
 */
public class PembayaranFrame extends javax.swing.JFrame {
    private String idSewaTerpilih;
    private int hitungDenda(String idSewa) {
    try {
        String sql = "SELECT tgl_jatuh_tempo, k.harga_per_bulan FROM sewa s JOIN kamar k ON s.no_kamar = k.no_kamar WHERE s.id_sewa = " + idSewa;
        java.sql.Connection conn = config.koneksi.configDB();
        java.sql.ResultSet res = conn.createStatement().executeQuery(sql);

        if (res.next()) {
            java.util.Date jatuhTempo = res.getDate("tgl_jatuh_tempo");
            int hargaKamar = res.getInt("harga_per_bulan");

            // --- BARU: Format Tanggal dan Tampilkan ---
            java.text.SimpleDateFormat formatter = new java.text.SimpleDateFormat("dd-MM-yyyy");
            txtJatuhTempo.setText(formatter.format(jatuhTempo));
            // ------------------------------------------

            java.util.Date hariIni = new java.util.Date();
            long diff = hariIni.getTime() - jatuhTempo.getTime();
            long selisihHari = diff / (24 * 60 * 60 * 1000);

            if (selisihHari > 0) {
                int dendaPerHari = 10000;
                int totalDenda = (int) (selisihHari * dendaPerHari);

                // Tampilkan denda dan total bayar
                txtDenda.setText(String.valueOf(totalDenda));
                txtTotalBayar.setText(String.valueOf(hargaKamar + totalDenda));
                return totalDenda;
            } else {
                // Tampilkan 0 jika tidak ada denda
                txtDenda.setText("0");
                txtTotalBayar.setText(String.valueOf(hargaKamar));
                return 0;
            }
        } else {
            // Jika ID Sewa tidak ditemukan
            txtDenda.setText("");
            txtTotalBayar.setText("");
            txtJatuhTempo.setText("");
            return 0;
        }
        } catch (Exception e) {
        System.err.println("Error hitung denda: " + e.getMessage());

        // --- PERBAIKAN: Reset fields di sini ---
        txtDenda.setText("");
        txtTotalBayar.setText("");
        txtJatuhTempo.setText("");
        // ------------------------------------

        return 0;
    }
}
    
    
    private void tampilNamaPenghuni() {
    try {
        java.sql.Connection conn = config.koneksi.configDB();
        
        // 1. OTOMATISASI STATUS: UPDATE status menjadi 'Belum Dibayar'
        //    Jika tgl_jatuh_tempo sudah lewat dari hari ini DAN statusnya masih 'Sudah Dibayar'
        String sqlCekStatus = "UPDATE sewa SET status_pembayaran = 'Belum Dibayar' WHERE tgl_jatuh_tempo < CURRENT_DATE() AND status_pembayaran = 'Sudah Dibayar'";
        conn.createStatement().executeUpdate(sqlCekStatus);
        
        // 2. Muat data NAMA Penghuni yang sedang aktif
        String sql = "SELECT s.id_sewa, p.nama_penghuni FROM sewa s JOIN penghuni p ON s.ktp_penghuni = p.ktp_penghuni";
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);

        cbSewa.removeAllItems();
        cbSewa.addItem("-- Pilih Nama Penghuni --"); // Ganti teks default

        while (res.next()) {
            cbSewa.addItem(res.getString("nama_penghuni"));
        }
    } catch (Exception e) {
        System.err.println("Error load Nama Penghuni: " + e.getMessage());
    }
}
    
    /**
     * Creates new form PembayaranFrame
     */
    public PembayaranFrame() {
        initComponents();
        tampilNamaPenghuni(); // Panggil fungsi untuk mengisi ComboBox saat form dibuka
    
        // Atur JTextField agar read-only
        txtDenda.setEditable(false);
        txtTotalBayar.setEditable(false);
        txtJatuhTempo.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        cbSewa = new javax.swing.JComboBox<>();
        txtJatuhTempo = new javax.swing.JTextField();
        txtTotalBayar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDenda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBayar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pembayaran"));

        btnClose.setBackground(new java.awt.Color(204, 204, 204));
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        cbSewa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSewaItemStateChanged(evt);
            }
        });

        jLabel3.setText("Total Bayar");

        jLabel1.setText("Jatuh Tempo");

        jLabel2.setText("Denda");

        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtJatuhTempo)
                            .addComponent(txtDenda)
                            .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBayar)
                    .addComponent(btnClose))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJatuhTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cbSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnBayar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose))
                .addContainerGap(205, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(116, 116, 116))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        if (idSewaTerpilih == null) {
        JOptionPane.showMessageDialog(this, "Pilih Penghuni terlebih dahulu.");
        return;
    }
    
    int konfirmasi = JOptionPane.showConfirmDialog(null, "Konfirmasi Pembayaran?", "Bayar", JOptionPane.YES_NO_OPTION);

    if (konfirmasi == JOptionPane.YES_OPTION) {
        try {
            // UPDATE: Set status ke 'Sudah Dibayar', perbarui tgl_jatuh_tempo (+1 bulan), dan tgl_bayar_terakhir (hari ini)
            String sqlUpdate = "UPDATE sewa SET tgl_jatuh_tempo = DATE_ADD(tgl_jatuh_tempo, INTERVAL 1 MONTH), tgl_bayar_terakhir = CURRENT_DATE(), status_pembayaran = 'Sudah Dibayar' WHERE id_sewa = ?";
            
            java.sql.Connection conn = config.koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sqlUpdate);
            pst.setString(1, idSewaTerpilih); // Gunakan ID Sewa yang disimpan dari ComboBox
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Pembayaran Berhasil Dicatat! Status: Sudah Dibayar.");
            
            // Refresh tampilan setelah bayar
            txtDenda.setText("");
            txtTotalBayar.setText("");
            txtJatuhTempo.setText("");
            tampilNamaPenghuni(); // Refresh ComboBox
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Mencatat Pembayaran: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnBayarActionPerformed

    private void cbSewaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSewaItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        String namaTerpilih = cbSewa.getSelectedItem().toString();
        
        if (!namaTerpilih.contains("--")) {
            try {
                // Cari ID Sewa berdasarkan Nama yang dipilih
                String sql = "SELECT s.id_sewa FROM sewa s JOIN penghuni p ON s.ktp_penghuni = p.ktp_penghuni WHERE p.nama_penghuni='" + namaTerpilih + "'";
                java.sql.Connection conn = config.koneksi.configDB();
                java.sql.ResultSet res = conn.createStatement().executeQuery(sql);
                
                if (res.next()) {
                    idSewaTerpilih = res.getString("id_sewa"); // Simpan ID Sewa
                    hitungDenda(idSewaTerpilih); // Gunakan ID Sewa yang disimpan
                }
            } catch (Exception e) {
                System.err.println("Error saat memilih Penghuni: " + e.getMessage());
            }
        } else {
            idSewaTerpilih = null;
            txtDenda.setText("");
            txtTotalBayar.setText("");
            txtJatuhTempo.setText("");
        }
    }
    }//GEN-LAST:event_cbSewaItemStateChanged

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PembayaranFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PembayaranFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PembayaranFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PembayaranFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PembayaranFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnClose;
    private javax.swing.JComboBox<String> cbSewa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDenda;
    private javax.swing.JTextField txtJatuhTempo;
    private javax.swing.JTextField txtTotalBayar;
    // End of variables declaration//GEN-END:variables

}
