/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.JOptionPane;

/**
 *
 * @author WINDOWS 11 PRO
 */
public class SewaFrame extends javax.swing.JFrame {
    private String idTerpilih;
    private String idSewaTerpilih;
    private String noKamarTerpilih;
    
    private void tampilKamar() {
        try {
            String sql = "SELECT no_kamar FROM kamar WHERE status='Kosong'";
            java.sql.Connection conn = (java.sql.Connection) config.koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            // --- Perbaikan di sini ---
            cbKamar.removeAllItems(); // Bersihkan item lama
            cbKamar.addItem("-- Pilih Kamar --"); // Tambahkan default item
            // --- Akhir Perbaikan ---

            while(res.next()) {
                cbKamar.addItem(res.getString("no_kamar"));
            }
        } catch (Exception e) {
            System.out.println("Error Load ComboBox Kamar: " + e.getMessage());
        }
    }
    
    private void tampilPenghuni() {
        try {
            String sql = "SELECT nama_penghuni FROM penghuni";
            java.sql.Connection conn = (java.sql.Connection) config.koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            cbPenghuni.removeAllItems();
            cbPenghuni.addItem("-- Pilih Penghuni --");

            while(res.next()) {
                cbPenghuni.addItem(res.getString("nama_penghuni"));
            }
        } catch (Exception e) {
            System.out.println("Error Load ComboBox Penghuni: " + e.getMessage());
        }
    }
        
    private void loadDataSewa() {
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
    model.addColumn("ID Sewa");
    model.addColumn("No. Kamar");
    model.addColumn("Nama Penghuni");
    model.addColumn("Tgl Masuk");
    model.addColumn("Status Bayar"); // <<< Kolom Baru Ditambahkan

    try {
        // Menggunakan JOIN dan mengambil kolom status_pembayaran
        String sql = "SELECT s.id_sewa, s.no_kamar, p.nama_penghuni, s.tgl_masuk, s.status_pembayaran FROM sewa s JOIN penghuni p ON s.ktp_penghuni = p.ktp_penghuni";
        java.sql.Connection conn = (java.sql.Connection) config.koneksi.configDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);

        while(res.next()) {
            // Kita harus mengambil 5 kolom sekarang
            model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5)});
        }
            tblSewa.setModel(model);
        } catch (Exception e) {
            System.out.println("Error Load Data Sewa: " + e.getMessage());
        }
    }
    
    private void tanggalOtomatis() {
        java.util.Date now = new java.util.Date();
        java.text.SimpleDateFormat formatter = new java.text.SimpleDateFormat("yyyy-MM-dd"); // Format SQL Date
        txtTglMasuk.setText(formatter.format(now));
        txtTglMasuk.setEnabled(false); // Jangan biarkan user mengedit tanggal
    }
    

    /**
     * Creates new form SewaFrame
     */
    public SewaFrame() {
        initComponents();
        tanggalOtomatis(); // Isi tanggal
        tampilKamar();     // Isi cbKamar
        tampilPenghuni();  // Isi cbPenghuni
        loadDataSewa();    // Tampilkan data sewa aktif
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbKamar = new javax.swing.JComboBox<>();
        cbPenghuni = new javax.swing.JComboBox<>();
        btnCheckOut = new javax.swing.JButton();
        btnCheckIn = new javax.swing.JButton();
        txtTglMasuk = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSewa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sewa Kamar"));

        cbPenghuni.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPenghuniItemStateChanged(evt);
            }
        });

        btnCheckOut.setText("Check Out");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });

        btnCheckIn.setText("Check In");
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });

        txtTglMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTglMasukActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(204, 204, 204));
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        tblSewa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Sewa", "No. Kamar", "Nama Penghuni", "Tgl Masuk", "Status"
            }
        ));
        tblSewa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSewaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSewa);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbPenghuni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCheckOut))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnClose))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTglMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTglMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCheckIn))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCheckOut)
                            .addComponent(btnClose)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbPenghuni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
        // TODO add your handling code here:
        // Tambahkan Validasi dasar
    if (cbKamar.getSelectedItem().toString().contains("--") || cbPenghuni.getSelectedItem().toString().contains("--") || idTerpilih == null) {
        JOptionPane.showMessageDialog(this, "Pilih Kamar dan Penghuni terlebih dahulu.");
        return;
    }

    try {
        java.sql.Connection conn = (java.sql.Connection) config.koneksi.configDB();

        // 1. Query INSERT dengan inisialisasi tgl_jatuh_tempo dan status_pembayaran
        String sqlSewa = "INSERT INTO sewa (no_kamar, ktp_penghuni, tgl_masuk, tgl_jatuh_tempo, tgl_bayar_terakhir, status_pembayaran) "
                       + "VALUES (?, ?, ?, DATE_ADD(?, INTERVAL 1 MONTH), ?, 'Belum Dibayar')";

        // 2. Update status kamar
        String sqlUpdate = "UPDATE kamar SET status='Terisi' WHERE no_kamar=?";

        // --- EKSEKUSI TRANSAKSI ---

        // Eksekusi Simpan Sewa
        java.sql.PreparedStatement pstSewa = conn.prepareStatement(sqlSewa);
        pstSewa.setString(1, cbKamar.getSelectedItem().toString());
        pstSewa.setString(2, idTerpilih); // KTP Penghuni
        pstSewa.setString(3, txtTglMasuk.getText()); // tgl_masuk
        pstSewa.setString(4, txtTglMasuk.getText()); // TGL MASUK (untuk DATE_ADD)
        pstSewa.setString(5, txtTglMasuk.getText()); // tgl_bayar_terakhir
        pstSewa.executeUpdate();

        // Eksekusi Update Kamar
        java.sql.PreparedStatement pstUpdate = conn.prepareStatement(sqlUpdate);
        pstUpdate.setString(1, cbKamar.getSelectedItem().toString());
        pstUpdate.executeUpdate();

        // NOTIFIKASI BERHASIL (Muncul setelah semua SQL sukses)
        JOptionPane.showMessageDialog(null, "Check-in Berhasil! Kamar " + cbKamar.getSelectedItem() + " kini terisi.");

        // Refresh Data Tabel Sewa dan ComboBox Kamar
        loadDataSewa();
        tampilKamar();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal Check-In: " + e.getMessage());
    }
    }//GEN-LAST:event_btnCheckInActionPerformed

    private void cbPenghuniItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPenghuniItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            try {
                String namaTerpilih = cbPenghuni.getSelectedItem().toString();

                // Mencari KTP berdasarkan Nama yang dipilih
                String sql = "SELECT ktp_penghuni FROM penghuni WHERE nama_penghuni='" + namaTerpilih + "'";
                java.sql.Connection conn = (java.sql.Connection) config.koneksi.configDB();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);

                if (res.next()) {
                    idTerpilih = res.getString("ktp_penghuni"); // Variabel global idTerpilih terisi di sini
                }
            } catch (Exception e) {
                System.err.println("Error saat memilih Penghuni: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_cbPenghuniItemStateChanged

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        // TODO add your handling code here:
        if (idSewaTerpilih == null) {
        JOptionPane.showMessageDialog(this, "Silakan pilih data sewa yang akan di Check-Out dari tabel.");
        return;
    }

    int konfirmasi = JOptionPane.showConfirmDialog(null,
                "Yakin ingin Check-Out kamar " + noKamarTerpilih + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

    if (konfirmasi == JOptionPane.YES_OPTION) {
        try {
            // 1. Query DELETE dari tabel sewa
            String sqlDelete = "DELETE FROM sewa WHERE id_sewa='" + idSewaTerpilih + "'";

            // 2. Query UPDATE status kamar menjadi 'Kosong'
            String sqlUpdate = "UPDATE kamar SET status='Kosong' WHERE no_kamar='" + noKamarTerpilih + "'";

            java.sql.Connection conn = (java.sql.Connection) config.koneksi.configDB();

            // Eksekusi Hapus Sewa
            java.sql.PreparedStatement pstDelete = conn.prepareStatement(sqlDelete);
            pstDelete.execute();

            // Eksekusi Update Kamar
            java.sql.PreparedStatement pstUpdate = conn.prepareStatement(sqlUpdate);
            pstUpdate.execute();

            // NOTIFIKASI BERHASIL
            JOptionPane.showMessageDialog(null, "Check-Out Berhasil! Kamar " + noKamarTerpilih + " kini KOSONG.");

            // Refresh tampilan
            loadDataSewa();
            tampilKamar();

            // Reset variabel terpilih
            idSewaTerpilih = null;
            noKamarTerpilih = null;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Check-Out: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void tblSewaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSewaMouseClicked
        // TODO add your handling code here:
        int baris = tblSewa.rowAtPoint(evt.getPoint());
    
        // Ambil data ID Sewa (Kolom 0) dan No. Kamar (Kolom 1)
        idSewaTerpilih = tblSewa.getModel().getValueAt(baris, 0).toString();
        noKamarTerpilih = tblSewa.getModel().getValueAt(baris, 1).toString();

        // Kita bisa tampilkan data ini ke console untuk debugging (opsional)
        System.out.println("ID Sewa Dipilih: " + idSewaTerpilih);
        System.out.println("No. Kamar Dipilih: " + noKamarTerpilih);
    }//GEN-LAST:event_tblSewaMouseClicked

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtTglMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTglMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTglMasukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SewaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SewaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SewaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SewaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SewaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnClose;
    private javax.swing.JComboBox<String> cbKamar;
    private javax.swing.JComboBox<String> cbPenghuni;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSewa;
    private javax.swing.JTextField txtTglMasuk;
    // End of variables declaration//GEN-END:variables
}
